{% set name = "jobard-daemon" %}
{% set version = "1.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/jobard/jobard_daemon/-/archive/{{ version }}/jobard_daemon-{{ version }}.tar.gz
  sha256: df3486b16dddb63a74a3d95f7e5f20c178fe871f71a2f20c962cac6f2e3d4213

build:
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - jobard-daemon = jobard_daemon.console.application:cli

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >=3.8
    - pydantic >=1.8.2,<1.9
    - click >=8.0.2,<8.0.3
    - jinja2 >2
    - asyncssh >=2.9.0,<3.0.0
    - asyncpg >=0.25.0
    - pyyaml >=6.0,<7
    - pandas

test:
  source_files:
    - tests
  imports:
    - jobard_daemon
  requires:
    - pytest >=6,<7
    - pytest-cov >=2,<3
    - coverage
  commands:
    - pytest --pyargs tests

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_daemon
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Job manager of the  Job Array Daemon.

extra:
  recipe-maintainers:
    - marie59
    - criou-cg
