{% set name = "jobard-daemon" %}
{% set version = "1.7.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/jobard/jobard_daemon/-/archive/{{ version }}/jobard_daemon-{{ version }}.tar.gz
  sha256: bf35ea827528205418095fc0dd661d99eb5b4697e5e541fa4e60139265a234d1

build:
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - jobard-daemon = jobard_daemon.console.application:cli

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >={{ python_min }}
    - pydantic >=1.8.2,<1.9
    - click >=8.0.2,<8.0.3
    - jinja2 >2
    - asyncssh >=2.9.0,<3.0.0
    - asyncpg >=0.25.0
    - pyyaml >=6.0,<7
    - pandas

test:
  source_files:
    - tests
  imports:
    - jobard_daemon
  requires:
    - pytest >=6,<7
    - pytest-cov >=2,<3
    - coverage
  commands:
    - pytest --pyargs tests

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_daemon
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Job manager of the  Job Array Daemon.

extra:
  recipe-maintainers:
    - marie59
    - criou-cg
